packages:
  - apps/*
  - packages/*
  - internal/*
  - internal/lint-configs/*
  - scripts/*
  - docs

catalog:
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.5
  '@changesets/git': ^3.0.4
  '@clack/prompts': ^0.11.0
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  '@eslint/js': ^9.31.0
  '@floating-ui/dom': ^1.5.3
  '@iconify-json/tabler': ^1.2.19
  '@intlify/unplugin-vue-i18n': ^6.0.8
  '@jspm/generator': ^2.6.2
  '@manypkg/get-packages': ^3.0.0
  '@pnpm/workspace.read-manifest': ^1000.2.0
  '@stencil/angular-output-target': ^0.8.4
  '@stencil/core': ^4.36.0
  '@stencil/react-output-target': ^0.5.3
  '@stencil/sass': ^3.0.12
  '@stencil/vue-output-target': ^0.10.8
  '@stylistic/stylelint-plugin': ^3.1.3
  '@tiptap/core': ^2.11.3
  '@tiptap/extension-font-family': ^2.11.3
  '@tiptap/extension-history': ^2.11.3
  '@tiptap/extension-mention': ^2.11.3
  '@tiptap/extension-placeholder': ^2.11.3
  '@tiptap/extension-text-style': ^2.11.3
  '@tiptap/extension-underline': ^2.11.3
  '@tiptap/pm': ^2.11.3
  '@tiptap/starter-kit': ^2.11.3
  '@types/archiver': ^6.0.3
  '@types/eslint': ^9.6.1
  '@types/html-minifier-terser': ^7.0.2
  '@types/jest': ^27.5.2
  '@types/js-beautify': ^1.13.3
  '@types/node': ^24.0.13
  '@typescript-eslint/eslint-plugin': ^8.37.0
  '@typescript-eslint/parser': ^8.37.0
  '@vite-pwa/vitepress': ^1.0.0
  '@vitejs/plugin-vue': ^6.0.0
  '@vitejs/plugin-vue-jsx': ^5.0.1
  '@vueuse/core': ^13.5.0
  archiver: ^7.0.1
  beautify: ^0.0.8
  cac: ^6.7.14
  chalk: ^5.4.1
  cheerio: ^1.1.0
  commitlint-plugin-function-rules: ^4.0.2
  concurrently: ^7.1.0
  consola: ^3.4.2
  cross-env: ^7.0.3
  cspell: ^9.1.5
  cz-git: ^1.12.0
  czg: ^1.12.0
  date-fns: ^2.29.3
  dayjs: ^1.11.13
  dompurify: ^3.0.6
  dotenv: ^17.2.0
  eslint: 9.31.0
  eslint-config-turbo: ^2.5.4
  eslint-plugin-command: ^3.3.1
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^51.4.0
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-n: ^17.21.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-prettier: ^5.5.1
  eslint-plugin-regexp: ^2.9.0
  eslint-plugin-unicorn: ^59.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^10.3.0
  execa: ^9.6.0
  find-up: ^7.0.0
  get-port: ^7.1.0
  globals: ^16.3.0
  html-minifier-terser: ^7.2.0
  husky: ^9.1.7
  is-ci: ^4.1.0
  jest: ^27.5.1
  jest-cli: ^27.5.1
  js-beautify: ^1.15.4
  jsonc-eslint-parser: ^2.4.0
  lint-staged: ^16.1.2
  lodash: ^4.17.21
  medium-zoom: ^1.1.0
  nitropack: ^2.12.0
  ora: ^8.2.0
  pkg-types: ^2.2.0
  postcss: ^8.5.6
  postcss-html: ^1.8.0
  postcss-scss: ^4.0.9
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: 0.6.14
  puppeteer: ^22.12.1
  resolve.exports: ^2.0.3
  rimraf: ^6.0.1
  rollup: ^4.45.0
  rollup-plugin-dotenv: ^0.5.0
  rollup-plugin-visualizer: ^6.0.3
  sass: ^1.89.2
  stylelint: 16.21.1
  stylelint-config-recess-order: ^7.1.0
  stylelint-config-recommended: ^16.0.0
  stylelint-config-recommended-scss: ^15.0.1
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^38.0.0
  stylelint-order: ^7.0.0
  stylelint-prettier: ^5.0.3
  stylelint-scss: ^6.12.1
  terser: ^5.43.1
  turbo: ^2.5.4
  typescript: ^5.8.3
  unbuild: ^3.5.0
  unocss: ^66.3.3
  unplugin-vue-components: ^28.8.0
  vite: ^7.0.4
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7
  vite-plugin-pwa: ^1.0.1
  vite-plugin-vue-devtools: ^7.7.7
  vitepress: ^1.6.3
  vitepress-plugin-group-icons: ^1.6.1
  vitest: ^3.2.4
  vue: ^3.5.17
  vue-eslint-parser: ^10.2.0

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
  - puppeteer
