packages:
  - apps/*
  - packages/*
  - internal/*
  - internal/lint-configs/*

catalog:
  prettier: ^3.6.2
  '@changesets/changelog-github': ^0.5.1
  '@changesets/cli': ^2.29.5
  unbuild: ^3.5.0
  vite: ^7.0.4
  turbo: ^2.5.4
  cross-env: ^7.0.3
  cspell: ^9.1.5
  husky: ^9.1.7
  lint-staged: ^16.1.2
  vitest: ^3.2.4
  typescript: ^5.8.3
  '@vitejs/plugin-vue': ^6.0.0
  '@vitejs/plugin-vue-jsx': ^5.0.1
  '@commitlint/cli': ^19.8.1
  '@commitlint/config-conventional': ^19.8.1
  commitlint-plugin-function-rules: ^4.0.2
  cz-git: ^1.12.0
  czg: ^1.12.0
  eslint-config-turbo: ^2.5.4
  eslint-plugin-command: ^3.3.1
  eslint-plugin-import-x: ^4.16.1
  '@eslint/js': ^9.31.0
  '@types/eslint': ^9.6.1
  '@typescript-eslint/eslint-plugin': ^8.36.0
  '@typescript-eslint/parser': ^8.36.0
  eslint: ^9.31.0
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-jsdoc: ^51.3.4
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-n: ^17.21.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-prettier: ^5.5.1
  eslint-plugin-regexp: ^2.9.0
  eslint-plugin-unicorn: ^59.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^10.3.0
  globals: ^16.3.0
  jsonc-eslint-parser: ^2.4.0
  vue-eslint-parser: ^10.2.0
  prettier-plugin-tailwindcss: ^0.6.14
  '@stylistic/stylelint-plugin': ^3.1.3
  stylelint-config-recess-order: ^7.1.0
  stylelint-scss: ^6.12.1
  postcss: ^8.5.6
  postcss-html: ^1.8.0
  postcss-scss: ^4.0.9
  stylelint: ^16.21.1
  stylelint-config-recommended: ^16.0.0
  stylelint-config-recommended-scss: ^15.0.1
  stylelint-config-recommended-vue: ^1.6.1
  stylelint-config-standard: ^38.0.0
  stylelint-order: ^7.0.0
  stylelint-prettier: ^5.0.3
  '@changesets/git': ^3.0.4
  '@manypkg/get-packages': ^3.0.0
  chalk: ^5.4.1
  consola: ^3.4.2
  dayjs: ^1.11.13
  execa: ^9.6.0
  find-up: ^7.0.0
  ora: ^8.2.0
  pkg-types: ^2.2.0
  rimraf: ^6.0.1
  '@intlify/unplugin-vue-i18n': ^6.0.8
  '@jspm/generator': ^2.6.2
  archiver: ^7.0.1
  cheerio: ^1.1.0
  get-port: ^7.1.0
  html-minifier-terser: ^7.2.0
  nitropack: ^2.11.13
  resolve.exports: ^2.0.3
  vite-plugin-pwa: ^1.0.1
  vite-plugin-vue-devtools: ^7.7.7
  '@pnpm/workspace.read-manifest': ^1000.2.0
  '@types/archiver': ^6.0.3
  '@types/html-minifier-terser': ^7.0.2
  dotenv: ^17.2.0
  rollup: ^4.45.0
  rollup-plugin-visualizer: ^6.0.3
  sass: ^1.89.2
  vite-plugin-compression: ^0.5.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-html: ^3.2.2
  vite-plugin-lazy-import: ^1.0.7

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - unrs-resolver

onlyBuiltDependencies:
  - esbuild
