name: Deploy Website on push

on:
  push:
    branches:
      - main

jobs:
  deploy-docs-ftp:
    name: Deploy Docs to GitHub Pages
    if: github.actor != 'dependabot[bot]' && !contains(github.event.head_commit.message, '[skip ci]') && github.repository == 'zanedeng/zanejs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build
        run: pnpm build

      - name: Deploy to zanedeng.github.io
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: /
          external_repository: zanedeng/zanedeng.github.io
          publish_branch: main # 或者 master，取决于你的目标仓库
          keep_files: false # 设置为 true 如果你想要保留旧文件


