name: Deploy Website on push

on:
  push:
    branches:
      - main

jobs:
  deploy-docs-ftp:
    name: Deploy Docs to GitHub Pages
    if: github.actor != 'dependabot[bot]' && !contains(github.event.head_commit.message, '[skip ci]') && github.repository == 'zanedeng/zanejs'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Build
        run: pnpm build

      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@target-branch
        env:
          SSH_DEPLOY_KEY: ${{ secrets.DEPLOY_TOKEN }}
        with:
          source-directory: ./docs/.vitepress/dist
          destination-github-username: 'zanedeng'
          destination-repository-name: 'zanedeng.github.io'
          user-email: zane.deng@foxmail.com
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main

      # - name: Deploy to zanedeng.github.io
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: /
      #     external_repository: zanedeng/zanedeng.github.io
      #     publish_branch: main # 或者 master，取决于你的目标仓库
      #     keep_files: false # 设置为 true 如果你想要保留旧文件


